package pl.factoriald.remastris.Entity;

import java.awt.font.NumericShaper;

public enum Setting {
    GAMEFIELD_WIDTH, GAMEFIELD_HEIGHT,
    TICKER_DELAY,

    GRAVITY1_DOWN,
    GRAVITY2_UP,
    GRAVITY3_LEFT,
    GRAVITY4_RIGHT,

    FIGURE_SET,
    FIGURE_STANDARD,
    FIGURE_ADVANCED,
    FIGURE_SET_1,
    FIGURE_SET_2,

    PREFERENCES_NAME,

    HAS_SETTINGS,

    DEFAULT_GAMEFIELD_MIN_WIDTH,
    DEFAULT_GAMEFIELD_MIN_HEIGHT,
    DEFAULT_GAMEFIELD_MAX_WIDTH,
    DEFAULT_GAMEFIELD_MAX_HEIGHT,

    DEFAULT_TICKER_MIN_DELAY,
    DEFAULT_TICKER_MAX_DELAY,

    DEFAULT_GRAVITY1_DOWN_UPGRADE,
    DEFAULT_GRAVITY1_UP_UPGRADE,
    DEFAULT_GRAVITY1_LEFT_UPGRADE,
    DEFAULT_GRAVITY1_RIGHT_UPGRADE,

    DEFAULT_SPECIAL_BUTTON_UPGRADE,

    CURRENT_GAMEFIELD_MIN_WIDTH ,
    CURRENT_GAMEFIELD_MIN_HEIGHT ,
    CURRENT_GAMEFIELD_MAX_WIDTH ,
    CURRENT_GAMEFIELD_MAX_HEIGHT ,
    CURRENT_GRAVITY1_DOWN_UPGRADE ,
    CURRENT_GRAVITY1_UP_UPGRADE ,
    CURRENT_GRAVITY1_LEFT_UPGRADE ,
    CURRENT_GRAVITY1_RIGHT_UPGRADE ,
    CURRENT_SPECIAL_BUTTON_UPGRADE,

    CURRENT_TICKER_MIN_DELAY,
    CURRENT_TICKER_MAX_DELAY,

    CURRENT_GAMEFIELD_WIDTH ,
    CURRENT_GAMEFIELD_HEIGHT ,
    CURRENT_GRAVITY_DOWN ,
    CURRENT_GRAVITY_UP ,
    CURRENT_GRAVITY_LEFT ,
    CURRENT_GRAVITY_RIGHT ,
    CURRENT_SPECIAL_BUTTON,

    CURRENT_TICKER_DELAY,


    LAST_SCORE
}
